local t = storage.ab_ungen
local J = AUTO_BELT.jobs
local s = game.surfaces["auto-belt-test"]
if not s then
  s = game.create_surface("auto-belt-test")
  s.generate_with_lab_tiles = true
  s.request_to_generate_chunks({0, 0}, 8)
  s.force_generate_chunk_requests()
end
local TIER = AUTO_BELT.tiers.get("transport-belt")
local ALL = {[0] = true, [1] = true, [2] = true, [3] = true}
local function restore()
  if t and t.budget then settings.global["auto-belt-search-budget"] = {value = t.budget} end
  storage.ab_ungen = nil
end
local function in_band(x, y)
  local cx, cy = math.floor(x / 32), math.floor(y / 32)
  return cx >= 6 and cx <= 24 and cy >= -100 and cy <= -94
end
if not t then
  local function gen(cx, cy) s.request_to_generate_chunks({cx * 32 + 16, cy * 32 + 16}, 0) end
  for cx = 0, 30 do gen(cx, -106) end
  for _, cx in ipairs({0, 1, 29, 30}) do
    for cy = -106, -97 do gen(cx, cy) end
  end
  s.force_generate_chunk_requests()
  for cx = 6, 24 do
    for cy = -100, -94 do
      if s.is_chunk_generated{cx, cy} then return "SKIP: the band chunk (" .. cx .. ", " .. cy .. ") was generated by the engine" end
    end
  end
  for _, c in ipairs({{0, -97}, {30, -97}, {15, -106}}) do
    if not s.is_chunk_generated{c[1], c[2]} then error("chunk " .. c[1] .. ", " .. c[2] .. " not generated") end
  end
  for _, e in pairs(s.find_entities{{0, -3115}, {40, -3065}}) do e.destroy() end
  for _, e in pairs(s.find_entities{{960, -3115}, {1000, -3065}}) do e.destroy() end
  storage.grid = nil
  local job = J.create{surface_index = s.index, force = "player", starts = {{x = 16, y = -3090, d = 1}},
    goal = {x = 976, y = -3090, headings = ALL, place = true}, tier = TIER, layout = "belts", placement = "free"}
  storage.ab_ungen = {job = job.id, tick = game.tick, budget = settings.global["auto-belt-search-budget"].value}
  settings.global["auto-belt-search-budget"] = {value = 600}
  return "WAIT: routing"
end
local job = storage.jobs[t.job]
if job and J.searching(job) then
  if game.tick - t.tick > 3000 then restore(); error("job still searching after 3000 ticks, stage " .. job.stage) end
  return "WAIT: routing"
end
restore()
if not job then error("job gone") end
local stage, key, ticks, reads = job.stage, job.error, game.tick - t.tick, job.chunk_reads
local entities = job.entities
J.remove(job)
if not (reads and reads > 0) then error("job read no chunks") end
if stage == "ready" then
  for _, x in ipairs(entities) do
    if in_band(x.x, x.y) then error("planned entity inside the ungenerated band at " .. x.x .. ", " .. x.y) end
  end
  return "PASS: route goes around the ungenerated band, " .. #entities .. " entities, " .. ticks .. " ticks"
end
if stage ~= "failed" then error("job ended " .. stage) end
if key ~= "auto-belt.no-route" and key ~= "auto-belt.search-limit" then error("unexpected error " .. tostring(key)) end
error("route did not go around the band: failed with " .. key .. " after " .. ticks .. " ticks")
